CREATE TABLE PM_GAME ( ID_GAME INTEGER PRIMARY KEY,
			NAME varchar(45) DEFAULT NULL,
			IMAGE varchar(100) DEFAULT NULL,
			LINK varchar(100) DEFAULT NULL,
			GENERATION INTEGER DEFAULT NULL );

CREATE TABLE PM_MOVE ( ID_MOVE INTEGER PRIMARY KEY,
		        NAME varchar(45) DEFAULT NULL,
			LINK varchar(100) DEFAULT NULL );

CREATE TABLE PM_MOVE_TYPE ( ID_MOVE_TYPE INTEGER PRIMARY KEY,
			     TYPE varchar(30) DEFAULT NULL,
			     DIFFICULTY INTEGER DEFAULT NULL );

CREATE TABLE PM_POKEMON ( ID_POKEMON INTEGER PRIMARY KEY,
			   NAME varchar(45) DEFAULT NULL,
			   IMAGE varchar(100) DEFAULT NULL,
			   ICON varchar(100) DEFAULT NULL,
			   LINK varchar(100) DEFAULT NULL,
			   ID_EVOLUTION INTEGER DEFAULT NULL );

CREATE TABLE RL_POKEMON_GAME ( ID_POKEMON INTEGER NOT NULL,
				ID_GAME INTEGER NOT NULL,
				PRIMARY KEY (ID_POKEMON, ID_GAME),
				CONSTRAINT FK_ID_POKEMON FOREIGN KEY (ID_POKEMON) REFERENCES PM_POKEMON (ID_POKEMON),
				CONSTRAINT FK_ID_GAME FOREIGN KEY (ID_GAME) REFERENCES PM_GAME (ID_GAME));

CREATE TABLE RL_POKEMON_MOVE_GAME (ID_POKEMON INTEGER NOT NULL DEFAULT '0',
  				    ID_GAME INTEGER NOT NULL DEFAULT '0',
				    ID_MOVE INTEGER NOT NULL DEFAULT '0',
				    LEVEL INTEGER DEFAULT NULL,
				    TYPE INTEGER DEFAULT NULL,
				    FOREIGN KEY (ID_POKEMON) REFERENCES PM_POKEMON (ID_POKEMON),
				    FOREIGN KEY (ID_MOVE) REFERENCES PM_MOVE (ID_MOVE),
				    FOREIGN KEY (ID_GAME) REFERENCES PM_GAME (ID_GAME));
