INSERT INTO PM_MOVE_TYPE VALUES (1,'Level Up',1);
INSERT INTO PM_MOVE_TYPE VALUES (2,'Machine',2);
INSERT INTO PM_MOVE_TYPE VALUES (3,'Move Tutor',3);
INSERT INTO PM_MOVE_TYPE VALUES (4,'Egg Move',4);
INSERT INTO PM_MOVE_TYPE VALUES (5,'Event',7);
INSERT INTO PM_MOVE_TYPE VALUES (6,'PokéWalker',5);
INSERT INTO PM_MOVE_TYPE VALUES (7,'Pokémon Battle Revolution',6);