INSERT INTO PM_MOVE VALUES  (1,'Pound','http://bulbapedia.bulbagarden.net/wiki/Pound_(move)');
INSERT INTO PM_MOVE VALUES  (2,'Karate Chop','http://bulbapedia.bulbagarden.net/wiki/Karate_Chop_(move)');
INSERT INTO PM_MOVE VALUES  (3,'DoubleSlap','http://bulbapedia.bulbagarden.net/wiki/DoubleSlap_(move)');
INSERT INTO PM_MOVE VALUES  (4,'Comet Punch','http://bulbapedia.bulbagarden.net/wiki/Comet_Punch_(move)');
INSERT INTO PM_MOVE VALUES  (5,'Mega Punch','http://bulbapedia.bulbagarden.net/wiki/Mega_Punch_(move)');
INSERT INTO PM_MOVE VALUES  (6,'Pay Day','http://bulbapedia.bulbagarden.net/wiki/Pay_Day_(move)');
INSERT INTO PM_MOVE VALUES  (7,'Fire Punch','http://bulbapedia.bulbagarden.net/wiki/Fire_Punch_(move)');
INSERT INTO PM_MOVE VALUES  (8,'Ice Punch','http://bulbapedia.bulbagarden.net/wiki/Ice_Punch_(move)');
INSERT INTO PM_MOVE VALUES  (9,'ThunderPunch','http://bulbapedia.bulbagarden.net/wiki/ThunderPunch_(move)');
INSERT INTO PM_MOVE VALUES  (10,'Scratch','http://bulbapedia.bulbagarden.net/wiki/Scratch_(move)');
INSERT INTO PM_MOVE VALUES  (11,'ViceGrip','http://bulbapedia.bulbagarden.net/wiki/ViceGrip_(move)');
INSERT INTO PM_MOVE VALUES  (12,'Guillotine','http://bulbapedia.bulbagarden.net/wiki/Guillotine_(move)');
INSERT INTO PM_MOVE VALUES  (13,'Razor Wind','http://bulbapedia.bulbagarden.net/wiki/Razor_Wind_(move)');
INSERT INTO PM_MOVE VALUES  (14,'Swords Dance','http://bulbapedia.bulbagarden.net/wiki/Swords_Dance_(move)');
INSERT INTO PM_MOVE VALUES  (15,'Cut','http://bulbapedia.bulbagarden.net/wiki/Cut_(move)');
INSERT INTO PM_MOVE VALUES  (16,'Gust','http://bulbapedia.bulbagarden.net/wiki/Gust_(move)');
INSERT INTO PM_MOVE VALUES  (17,'Wing Attack','http://bulbapedia.bulbagarden.net/wiki/Wing_Attack_(move)');
INSERT INTO PM_MOVE VALUES  (18,'Whirlwind','http://bulbapedia.bulbagarden.net/wiki/Whirlwind_(move)');
INSERT INTO PM_MOVE VALUES  (19,'Fly','http://bulbapedia.bulbagarden.net/wiki/Fly_(move)');
INSERT INTO PM_MOVE VALUES  (20,'Bind','http://bulbapedia.bulbagarden.net/wiki/Bind_(move)');
INSERT INTO PM_MOVE VALUES  (21,'Slam','http://bulbapedia.bulbagarden.net/wiki/Slam_(move)');
INSERT INTO PM_MOVE VALUES  (22,'Vine Whip','http://bulbapedia.bulbagarden.net/wiki/Vine_Whip_(move)');
INSERT INTO PM_MOVE VALUES  (23,'Stomp','http://bulbapedia.bulbagarden.net/wiki/Stomp_(move)');
INSERT INTO PM_MOVE VALUES  (24,'Double Kick','http://bulbapedia.bulbagarden.net/wiki/Double_Kick_(move)');
INSERT INTO PM_MOVE VALUES  (25,'Mega Kick','http://bulbapedia.bulbagarden.net/wiki/Mega_Kick_(move)');
INSERT INTO PM_MOVE VALUES  (26,'Jump Kick','http://bulbapedia.bulbagarden.net/wiki/Jump_Kick_(move)');
INSERT INTO PM_MOVE VALUES  (27,'Rolling Kick','http://bulbapedia.bulbagarden.net/wiki/Rolling_Kick_(move)');
INSERT INTO PM_MOVE VALUES  (28,'Sand-Attack','http://bulbapedia.bulbagarden.net/wiki/Sand-Attack_(move)');
INSERT INTO PM_MOVE VALUES  (29,'Headbutt','http://bulbapedia.bulbagarden.net/wiki/Headbutt_(move)');
INSERT INTO PM_MOVE VALUES  (30,'Horn Attack','http://bulbapedia.bulbagarden.net/wiki/Horn_Attack_(move)');
INSERT INTO PM_MOVE VALUES  (31,'Fury Attack','http://bulbapedia.bulbagarden.net/wiki/Fury_Attack_(move)');
INSERT INTO PM_MOVE VALUES  (32,'Horn Drill','http://bulbapedia.bulbagarden.net/wiki/Horn_Drill_(move)');
INSERT INTO PM_MOVE VALUES  (33,'Tackle','http://bulbapedia.bulbagarden.net/wiki/Tackle_(move)');
INSERT INTO PM_MOVE VALUES  (34,'Body Slam','http://bulbapedia.bulbagarden.net/wiki/Body_Slam_(move)');
INSERT INTO PM_MOVE VALUES  (35,'Wrap','http://bulbapedia.bulbagarden.net/wiki/Wrap_(move)');
INSERT INTO PM_MOVE VALUES  (36,'Take Down','http://bulbapedia.bulbagarden.net/wiki/Take_Down_(move)');
INSERT INTO PM_MOVE VALUES  (37,'Thrash','http://bulbapedia.bulbagarden.net/wiki/Thrash_(move)');
INSERT INTO PM_MOVE VALUES  (38,'Double-Edge','http://bulbapedia.bulbagarden.net/wiki/Double-Edge_(move)');
INSERT INTO PM_MOVE VALUES  (39,'Tail Whip','http://bulbapedia.bulbagarden.net/wiki/Tail_Whip_(move)');
INSERT INTO PM_MOVE VALUES  (40,'Poison Sting','http://bulbapedia.bulbagarden.net/wiki/Poison_Sting_(move)');
INSERT INTO PM_MOVE VALUES  (41,'Twineedle','http://bulbapedia.bulbagarden.net/wiki/Twineedle_(move)');
INSERT INTO PM_MOVE VALUES  (42,'Pin Missile','http://bulbapedia.bulbagarden.net/wiki/Pin_Missile_(move)');
INSERT INTO PM_MOVE VALUES  (43,'Leer','http://bulbapedia.bulbagarden.net/wiki/Leer_(move)');
INSERT INTO PM_MOVE VALUES  (44,'Bite','http://bulbapedia.bulbagarden.net/wiki/Bite_(move)');
INSERT INTO PM_MOVE VALUES  (45,'Growl','http://bulbapedia.bulbagarden.net/wiki/Growl_(move)');
INSERT INTO PM_MOVE VALUES  (46,'Roar','http://bulbapedia.bulbagarden.net/wiki/Roar_(move)');
INSERT INTO PM_MOVE VALUES  (47,'Sing','http://bulbapedia.bulbagarden.net/wiki/Sing_(move)');
INSERT INTO PM_MOVE VALUES  (48,'Supersonic','http://bulbapedia.bulbagarden.net/wiki/Supersonic_(move)');
INSERT INTO PM_MOVE VALUES  (49,'SonicBoom','http://bulbapedia.bulbagarden.net/wiki/SonicBoom_(move)');
INSERT INTO PM_MOVE VALUES  (50,'Disable','http://bulbapedia.bulbagarden.net/wiki/Disable_(move)');
INSERT INTO PM_MOVE VALUES  (51,'Acid','http://bulbapedia.bulbagarden.net/wiki/Acid_(move)');
INSERT INTO PM_MOVE VALUES  (52,'Ember','http://bulbapedia.bulbagarden.net/wiki/Ember_(move)');
INSERT INTO PM_MOVE VALUES  (53,'Flamethrower','http://bulbapedia.bulbagarden.net/wiki/Flamethrower_(move)');
INSERT INTO PM_MOVE VALUES  (54,'Mist','http://bulbapedia.bulbagarden.net/wiki/Mist_(move)');
INSERT INTO PM_MOVE VALUES  (55,'Water Gun','http://bulbapedia.bulbagarden.net/wiki/Water_Gun_(move)');
INSERT INTO PM_MOVE VALUES  (56,'Hydro Pump','http://bulbapedia.bulbagarden.net/wiki/Hydro_Pump_(move)');
INSERT INTO PM_MOVE VALUES  (57,'Surf','http://bulbapedia.bulbagarden.net/wiki/Surf_(move)');
INSERT INTO PM_MOVE VALUES  (58,'Ice Beam','http://bulbapedia.bulbagarden.net/wiki/Ice_Beam_(move)');
INSERT INTO PM_MOVE VALUES  (59,'Blizzard','http://bulbapedia.bulbagarden.net/wiki/Blizzard_(move)');
INSERT INTO PM_MOVE VALUES  (60,'Psybeam','http://bulbapedia.bulbagarden.net/wiki/Psybeam_(move)');
INSERT INTO PM_MOVE VALUES  (61,'BubbleBeam','http://bulbapedia.bulbagarden.net/wiki/BubbleBeam_(move)');
INSERT INTO PM_MOVE VALUES  (62,'Aurora Beam','http://bulbapedia.bulbagarden.net/wiki/Aurora_Beam_(move)');
INSERT INTO PM_MOVE VALUES  (63,'Hyper Beam','http://bulbapedia.bulbagarden.net/wiki/Hyper_Beam_(move)');
INSERT INTO PM_MOVE VALUES  (64,'Peck','http://bulbapedia.bulbagarden.net/wiki/Peck_(move)');
INSERT INTO PM_MOVE VALUES  (65,'Drill Peck','http://bulbapedia.bulbagarden.net/wiki/Drill_Peck_(move)');
INSERT INTO PM_MOVE VALUES  (66,'Submission','http://bulbapedia.bulbagarden.net/wiki/Submission_(move)');
INSERT INTO PM_MOVE VALUES  (67,'Low Kick','http://bulbapedia.bulbagarden.net/wiki/Low_Kick_(move)');
INSERT INTO PM_MOVE VALUES  (68,'Counter','http://bulbapedia.bulbagarden.net/wiki/Counter_(move)');
INSERT INTO PM_MOVE VALUES  (69,'Seismic Toss','http://bulbapedia.bulbagarden.net/wiki/Seismic_Toss_(move)');
INSERT INTO PM_MOVE VALUES  (70,'Strength','http://bulbapedia.bulbagarden.net/wiki/Strength_(move)');
INSERT INTO PM_MOVE VALUES  (71,'Absorb','http://bulbapedia.bulbagarden.net/wiki/Absorb_(move)');
INSERT INTO PM_MOVE VALUES  (72,'Mega Drain','http://bulbapedia.bulbagarden.net/wiki/Mega_Drain_(move)');
INSERT INTO PM_MOVE VALUES  (73,'Leech Seed','http://bulbapedia.bulbagarden.net/wiki/Leech_Seed_(move)');
INSERT INTO PM_MOVE VALUES  (74,'Growth','http://bulbapedia.bulbagarden.net/wiki/Growth_(move)');
INSERT INTO PM_MOVE VALUES  (75,'Razor Leaf','http://bulbapedia.bulbagarden.net/wiki/Razor_Leaf_(move)');
INSERT INTO PM_MOVE VALUES  (76,'SolarBeam','http://bulbapedia.bulbagarden.net/wiki/SolarBeam_(move)');
INSERT INTO PM_MOVE VALUES  (77,'PoisonPowder','http://bulbapedia.bulbagarden.net/wiki/PoisonPowder_(move)');
INSERT INTO PM_MOVE VALUES  (78,'Stun Spore','http://bulbapedia.bulbagarden.net/wiki/Stun_Spore_(move)');
INSERT INTO PM_MOVE VALUES  (79,'Sleep Powder','http://bulbapedia.bulbagarden.net/wiki/Sleep_Powder_(move)');
INSERT INTO PM_MOVE VALUES  (80,'Petal Dance','http://bulbapedia.bulbagarden.net/wiki/Petal_Dance_(move)');
INSERT INTO PM_MOVE VALUES  (81,'String Shot','http://bulbapedia.bulbagarden.net/wiki/String_Shot_(move)');
INSERT INTO PM_MOVE VALUES  (82,'Dragon Rage','http://bulbapedia.bulbagarden.net/wiki/Dragon_Rage_(move)');
INSERT INTO PM_MOVE VALUES  (83,'Fire Spin','http://bulbapedia.bulbagarden.net/wiki/Fire_Spin_(move)');
INSERT INTO PM_MOVE VALUES  (84,'ThunderShock','http://bulbapedia.bulbagarden.net/wiki/ThunderShock_(move)');
INSERT INTO PM_MOVE VALUES  (85,'Thunderbolt','http://bulbapedia.bulbagarden.net/wiki/Thunderbolt_(move)');
INSERT INTO PM_MOVE VALUES  (86,'Thunder Wave','http://bulbapedia.bulbagarden.net/wiki/Thunder_Wave_(move)');
INSERT INTO PM_MOVE VALUES  (87,'Thunder','http://bulbapedia.bulbagarden.net/wiki/Thunder_(move)');
INSERT INTO PM_MOVE VALUES  (88,'Rock Throw','http://bulbapedia.bulbagarden.net/wiki/Rock_Throw_(move)');
INSERT INTO PM_MOVE VALUES  (89,'Earthquake','http://bulbapedia.bulbagarden.net/wiki/Earthquake_(move)');
INSERT INTO PM_MOVE VALUES  (90,'Fissure','http://bulbapedia.bulbagarden.net/wiki/Fissure_(move)');
INSERT INTO PM_MOVE VALUES  (91,'Dig','http://bulbapedia.bulbagarden.net/wiki/Dig_(move)');
INSERT INTO PM_MOVE VALUES  (92,'Toxic','http://bulbapedia.bulbagarden.net/wiki/Toxic_(move)');
INSERT INTO PM_MOVE VALUES  (93,'Confusion','http://bulbapedia.bulbagarden.net/wiki/Confusion_(move)');
INSERT INTO PM_MOVE VALUES  (94,'Psychic','http://bulbapedia.bulbagarden.net/wiki/Psychic_(move)');
INSERT INTO PM_MOVE VALUES  (95,'Hypnosis','http://bulbapedia.bulbagarden.net/wiki/Hypnosis_(move)');
INSERT INTO PM_MOVE VALUES  (96,'Meditate','http://bulbapedia.bulbagarden.net/wiki/Meditate_(move)');
INSERT INTO PM_MOVE VALUES  (97,'Agility','http://bulbapedia.bulbagarden.net/wiki/Agility_(move)');
INSERT INTO PM_MOVE VALUES  (98,'Quick Attack','http://bulbapedia.bulbagarden.net/wiki/Quick_Attack_(move)');
INSERT INTO PM_MOVE VALUES  (99,'Rage','http://bulbapedia.bulbagarden.net/wiki/Rage_(move)');
INSERT INTO PM_MOVE VALUES  (100,'Teleport','http://bulbapedia.bulbagarden.net/wiki/Teleport_(move)');
INSERT INTO PM_MOVE VALUES  (101,'Night Shade','http://bulbapedia.bulbagarden.net/wiki/Night_Shade_(move)');
INSERT INTO PM_MOVE VALUES  (102,'Mimic','http://bulbapedia.bulbagarden.net/wiki/Mimic_(move)');
INSERT INTO PM_MOVE VALUES  (103,'Screech','http://bulbapedia.bulbagarden.net/wiki/Screech_(move)');
INSERT INTO PM_MOVE VALUES  (104,'Double Team','http://bulbapedia.bulbagarden.net/wiki/Double_Team_(move)');
INSERT INTO PM_MOVE VALUES  (105,'Recover','http://bulbapedia.bulbagarden.net/wiki/Recover_(move)');
INSERT INTO PM_MOVE VALUES  (106,'Harden','http://bulbapedia.bulbagarden.net/wiki/Harden_(move)');
INSERT INTO PM_MOVE VALUES  (107,'Minimize','http://bulbapedia.bulbagarden.net/wiki/Minimize_(move)');
INSERT INTO PM_MOVE VALUES  (108,'SmokeScreen','http://bulbapedia.bulbagarden.net/wiki/SmokeScreen_(move)');
INSERT INTO PM_MOVE VALUES  (109,'Confuse Ray','http://bulbapedia.bulbagarden.net/wiki/Confuse_Ray_(move)');
INSERT INTO PM_MOVE VALUES  (110,'Withdraw','http://bulbapedia.bulbagarden.net/wiki/Withdraw_(move)');
INSERT INTO PM_MOVE VALUES  (111,'Defense Curl','http://bulbapedia.bulbagarden.net/wiki/Defense_Curl_(move)');
INSERT INTO PM_MOVE VALUES  (112,'Barrier','http://bulbapedia.bulbagarden.net/wiki/Barrier_(move)');
INSERT INTO PM_MOVE VALUES  (113,'Light Screen','http://bulbapedia.bulbagarden.net/wiki/Light_Screen_(move)');
INSERT INTO PM_MOVE VALUES  (114,'Haze','http://bulbapedia.bulbagarden.net/wiki/Haze_(move)');
INSERT INTO PM_MOVE VALUES  (115,'Reflect','http://bulbapedia.bulbagarden.net/wiki/Reflect_(move)');
INSERT INTO PM_MOVE VALUES  (116,'Focus Energy','http://bulbapedia.bulbagarden.net/wiki/Focus_Energy_(move)');
INSERT INTO PM_MOVE VALUES  (117,'Bide','http://bulbapedia.bulbagarden.net/wiki/Bide_(move)');
INSERT INTO PM_MOVE VALUES  (118,'Metronome','http://bulbapedia.bulbagarden.net/wiki/Metronome_(move)');
INSERT INTO PM_MOVE VALUES  (119,'Mirror Move','http://bulbapedia.bulbagarden.net/wiki/Mirror_Move_(move)');
INSERT INTO PM_MOVE VALUES  (120,'Selfdestruct','http://bulbapedia.bulbagarden.net/wiki/Selfdestruct_(move)');
INSERT INTO PM_MOVE VALUES  (121,'Egg Bomb','http://bulbapedia.bulbagarden.net/wiki/Egg_Bomb_(move)');
INSERT INTO PM_MOVE VALUES  (122,'Lick','http://bulbapedia.bulbagarden.net/wiki/Lick_(move)');
INSERT INTO PM_MOVE VALUES  (123,'Smog','http://bulbapedia.bulbagarden.net/wiki/Smog_(move)');
INSERT INTO PM_MOVE VALUES  (124,'Sludge','http://bulbapedia.bulbagarden.net/wiki/Sludge_(move)');
INSERT INTO PM_MOVE VALUES  (125,'Bone Club','http://bulbapedia.bulbagarden.net/wiki/Bone_Club_(move)');
INSERT INTO PM_MOVE VALUES  (126,'Fire Blast','http://bulbapedia.bulbagarden.net/wiki/Fire_Blast_(move)');
INSERT INTO PM_MOVE VALUES  (127,'Waterfall','http://bulbapedia.bulbagarden.net/wiki/Waterfall_(move)');
INSERT INTO PM_MOVE VALUES  (128,'Clamp','http://bulbapedia.bulbagarden.net/wiki/Clamp_(move)');
INSERT INTO PM_MOVE VALUES  (129,'Swift','http://bulbapedia.bulbagarden.net/wiki/Swift_(move)');
INSERT INTO PM_MOVE VALUES  (130,'Skull Bash','http://bulbapedia.bulbagarden.net/wiki/Skull_Bash_(move)');
INSERT INTO PM_MOVE VALUES  (131,'Spike Cannon','http://bulbapedia.bulbagarden.net/wiki/Spike_Cannon_(move)');
INSERT INTO PM_MOVE VALUES  (132,'Constrict','http://bulbapedia.bulbagarden.net/wiki/Constrict_(move)');
INSERT INTO PM_MOVE VALUES  (133,'Amnesia','http://bulbapedia.bulbagarden.net/wiki/Amnesia_(move)');
INSERT INTO PM_MOVE VALUES  (134,'Kinesis','http://bulbapedia.bulbagarden.net/wiki/Kinesis_(move)');
INSERT INTO PM_MOVE VALUES  (135,'Softboiled','http://bulbapedia.bulbagarden.net/wiki/Softboiled_(move)');
INSERT INTO PM_MOVE VALUES  (136,'Hi Jump Kick','http://bulbapedia.bulbagarden.net/wiki/Hi_Jump_Kick_(move)');
INSERT INTO PM_MOVE VALUES  (137,'Glare','http://bulbapedia.bulbagarden.net/wiki/Glare_(move)');
INSERT INTO PM_MOVE VALUES  (138,'Dream Eater','http://bulbapedia.bulbagarden.net/wiki/Dream_Eater_(move)');
INSERT INTO PM_MOVE VALUES  (139,'Poison Gas','http://bulbapedia.bulbagarden.net/wiki/Poison_Gas_(move)');
INSERT INTO PM_MOVE VALUES  (140,'Barrage','http://bulbapedia.bulbagarden.net/wiki/Barrage_(move)');
INSERT INTO PM_MOVE VALUES  (141,'Leech Life','http://bulbapedia.bulbagarden.net/wiki/Leech_Life_(move)');
INSERT INTO PM_MOVE VALUES  (142,'Lovely Kiss','http://bulbapedia.bulbagarden.net/wiki/Lovely_Kiss_(move)');
INSERT INTO PM_MOVE VALUES  (143,'Sky Attack','http://bulbapedia.bulbagarden.net/wiki/Sky_Attack_(move)');
INSERT INTO PM_MOVE VALUES  (144,'Transform','http://bulbapedia.bulbagarden.net/wiki/Transform_(move)');
INSERT INTO PM_MOVE VALUES  (145,'Bubble','http://bulbapedia.bulbagarden.net/wiki/Bubble_(move)');
INSERT INTO PM_MOVE VALUES  (146,'Dizzy Punch','http://bulbapedia.bulbagarden.net/wiki/Dizzy_Punch_(move)');
INSERT INTO PM_MOVE VALUES  (147,'Spore','http://bulbapedia.bulbagarden.net/wiki/Spore_(move)');
INSERT INTO PM_MOVE VALUES  (148,'Flash','http://bulbapedia.bulbagarden.net/wiki/Flash_(move)');
INSERT INTO PM_MOVE VALUES  (149,'Psywave','http://bulbapedia.bulbagarden.net/wiki/Psywave_(move)');
INSERT INTO PM_MOVE VALUES  (150,'Splash','http://bulbapedia.bulbagarden.net/wiki/Splash_(move)');
INSERT INTO PM_MOVE VALUES  (151,'Acid Armor','http://bulbapedia.bulbagarden.net/wiki/Acid_Armor_(move)');
INSERT INTO PM_MOVE VALUES  (152,'Crabhammer','http://bulbapedia.bulbagarden.net/wiki/Crabhammer_(move)');
INSERT INTO PM_MOVE VALUES  (153,'Explosion','http://bulbapedia.bulbagarden.net/wiki/Explosion_(move)');
INSERT INTO PM_MOVE VALUES  (154,'Fury Swipes','http://bulbapedia.bulbagarden.net/wiki/Fury_Swipes_(move)');
INSERT INTO PM_MOVE VALUES  (155,'Bonemerang','http://bulbapedia.bulbagarden.net/wiki/Bonemerang_(move)');
INSERT INTO PM_MOVE VALUES  (156,'Rest','http://bulbapedia.bulbagarden.net/wiki/Rest_(move)');
INSERT INTO PM_MOVE VALUES  (157,'Rock Slide','http://bulbapedia.bulbagarden.net/wiki/Rock_Slide_(move)');
INSERT INTO PM_MOVE VALUES  (158,'Hyper Fang','http://bulbapedia.bulbagarden.net/wiki/Hyper_Fang_(move)');
INSERT INTO PM_MOVE VALUES  (159,'Sharpen','http://bulbapedia.bulbagarden.net/wiki/Sharpen_(move)');
INSERT INTO PM_MOVE VALUES  (160,'Conversion','http://bulbapedia.bulbagarden.net/wiki/Conversion_(move)');
INSERT INTO PM_MOVE VALUES  (161,'Tri Attack','http://bulbapedia.bulbagarden.net/wiki/Tri_Attack_(move)');
INSERT INTO PM_MOVE VALUES  (162,'Super Fang','http://bulbapedia.bulbagarden.net/wiki/Super_Fang_(move)');
INSERT INTO PM_MOVE VALUES  (163,'Slash','http://bulbapedia.bulbagarden.net/wiki/Slash_(move)');
INSERT INTO PM_MOVE VALUES  (164,'Substitute','http://bulbapedia.bulbagarden.net/wiki/Substitute_(move)');
INSERT INTO PM_MOVE VALUES  (165,'Struggle','http://bulbapedia.bulbagarden.net/wiki/Struggle_(move)');
INSERT INTO PM_MOVE VALUES  (166,'Sketch','http://bulbapedia.bulbagarden.net/wiki/Sketch_(move)');
INSERT INTO PM_MOVE VALUES  (167,'Triple Kick','http://bulbapedia.bulbagarden.net/wiki/Triple_Kick_(move)');
INSERT INTO PM_MOVE VALUES  (168,'Thief','http://bulbapedia.bulbagarden.net/wiki/Thief_(move)');
INSERT INTO PM_MOVE VALUES  (169,'Spider Web','http://bulbapedia.bulbagarden.net/wiki/Spider_Web_(move)');
INSERT INTO PM_MOVE VALUES  (170,'Mind Reader','http://bulbapedia.bulbagarden.net/wiki/Mind_Reader_(move)');
INSERT INTO PM_MOVE VALUES  (171,'Nightmare','http://bulbapedia.bulbagarden.net/wiki/Nightmare_(move)');
INSERT INTO PM_MOVE VALUES  (172,'Flame Wheel','http://bulbapedia.bulbagarden.net/wiki/Flame_Wheel_(move)');
INSERT INTO PM_MOVE VALUES  (173,'Snore','http://bulbapedia.bulbagarden.net/wiki/Snore_(move)');
INSERT INTO PM_MOVE VALUES  (174,'Curse','http://bulbapedia.bulbagarden.net/wiki/Curse_(move)');
INSERT INTO PM_MOVE VALUES  (175,'Flail','http://bulbapedia.bulbagarden.net/wiki/Flail_(move)');
INSERT INTO PM_MOVE VALUES  (176,'Conversion 2','http://bulbapedia.bulbagarden.net/wiki/Conversion_2_(move)');
INSERT INTO PM_MOVE VALUES  (177,'Aeroblast','http://bulbapedia.bulbagarden.net/wiki/Aeroblast_(move)');
INSERT INTO PM_MOVE VALUES  (178,'Cotton Spore','http://bulbapedia.bulbagarden.net/wiki/Cotton_Spore_(move)');
INSERT INTO PM_MOVE VALUES  (179,'Reversal','http://bulbapedia.bulbagarden.net/wiki/Reversal_(move)');
INSERT INTO PM_MOVE VALUES  (180,'Spite','http://bulbapedia.bulbagarden.net/wiki/Spite_(move)');
INSERT INTO PM_MOVE VALUES  (181,'Powder Snow','http://bulbapedia.bulbagarden.net/wiki/Powder_Snow_(move)');
INSERT INTO PM_MOVE VALUES  (182,'Protect','http://bulbapedia.bulbagarden.net/wiki/Protect_(move)');
INSERT INTO PM_MOVE VALUES  (183,'Mach Punch','http://bulbapedia.bulbagarden.net/wiki/Mach_Punch_(move)');
INSERT INTO PM_MOVE VALUES  (184,'Scary Face','http://bulbapedia.bulbagarden.net/wiki/Scary_Face_(move)');
INSERT INTO PM_MOVE VALUES  (185,'Faint Attack','http://bulbapedia.bulbagarden.net/wiki/Faint_Attack_(move)');
INSERT INTO PM_MOVE VALUES  (186,'Sweet Kiss','http://bulbapedia.bulbagarden.net/wiki/Sweet_Kiss_(move)');
INSERT INTO PM_MOVE VALUES  (187,'Belly Drum','http://bulbapedia.bulbagarden.net/wiki/Belly_Drum_(move)');
INSERT INTO PM_MOVE VALUES  (188,'Sludge Bomb','http://bulbapedia.bulbagarden.net/wiki/Sludge_Bomb_(move)');
INSERT INTO PM_MOVE VALUES  (189,'Mud-Slap','http://bulbapedia.bulbagarden.net/wiki/Mud-Slap_(move)');
INSERT INTO PM_MOVE VALUES  (190,'Octazooka','http://bulbapedia.bulbagarden.net/wiki/Octazooka_(move)');
INSERT INTO PM_MOVE VALUES  (191,'Spikes','http://bulbapedia.bulbagarden.net/wiki/Spikes_(move)');
INSERT INTO PM_MOVE VALUES  (192,'Zap Cannon','http://bulbapedia.bulbagarden.net/wiki/Zap_Cannon_(move)');
INSERT INTO PM_MOVE VALUES  (193,'Foresight','http://bulbapedia.bulbagarden.net/wiki/Foresight_(move)');
INSERT INTO PM_MOVE VALUES  (194,'Destiny Bond','http://bulbapedia.bulbagarden.net/wiki/Destiny_Bond_(move)');
INSERT INTO PM_MOVE VALUES  (195,'Perish Song','http://bulbapedia.bulbagarden.net/wiki/Perish_Song_(move)');
INSERT INTO PM_MOVE VALUES  (196,'Icy Wind','http://bulbapedia.bulbagarden.net/wiki/Icy_Wind_(move)');
INSERT INTO PM_MOVE VALUES  (197,'Detect','http://bulbapedia.bulbagarden.net/wiki/Detect_(move)');
INSERT INTO PM_MOVE VALUES  (198,'Bone Rush','http://bulbapedia.bulbagarden.net/wiki/Bone_Rush_(move)');
INSERT INTO PM_MOVE VALUES  (199,'Lock-On','http://bulbapedia.bulbagarden.net/wiki/Lock-On_(move)');
INSERT INTO PM_MOVE VALUES  (200,'Outrage','http://bulbapedia.bulbagarden.net/wiki/Outrage_(move)');
INSERT INTO PM_MOVE VALUES  (201,'Sandstorm','http://bulbapedia.bulbagarden.net/wiki/Sandstorm_(move)');
INSERT INTO PM_MOVE VALUES  (202,'Giga Drain','http://bulbapedia.bulbagarden.net/wiki/Giga_Drain_(move)');
INSERT INTO PM_MOVE VALUES  (203,'Endure','http://bulbapedia.bulbagarden.net/wiki/Endure_(move)');
INSERT INTO PM_MOVE VALUES  (204,'Charm','http://bulbapedia.bulbagarden.net/wiki/Charm_(move)');
INSERT INTO PM_MOVE VALUES  (205,'Rollout','http://bulbapedia.bulbagarden.net/wiki/Rollout_(move)');
INSERT INTO PM_MOVE VALUES  (206,'False Swipe','http://bulbapedia.bulbagarden.net/wiki/False_Swipe_(move)');
INSERT INTO PM_MOVE VALUES  (207,'Swagger','http://bulbapedia.bulbagarden.net/wiki/Swagger_(move)');
INSERT INTO PM_MOVE VALUES  (208,'Milk Drink','http://bulbapedia.bulbagarden.net/wiki/Milk_Drink_(move)');
INSERT INTO PM_MOVE VALUES  (209,'Spark','http://bulbapedia.bulbagarden.net/wiki/Spark_(move)');
INSERT INTO PM_MOVE VALUES  (210,'Fury Cutter','http://bulbapedia.bulbagarden.net/wiki/Fury_Cutter_(move)');
INSERT INTO PM_MOVE VALUES  (211,'Steel Wing','http://bulbapedia.bulbagarden.net/wiki/Steel_Wing_(move)');
INSERT INTO PM_MOVE VALUES  (212,'Mean Look','http://bulbapedia.bulbagarden.net/wiki/Mean_Look_(move)');
INSERT INTO PM_MOVE VALUES  (213,'Attract','http://bulbapedia.bulbagarden.net/wiki/Attract_(move)');
INSERT INTO PM_MOVE VALUES  (214,'Sleep Talk','http://bulbapedia.bulbagarden.net/wiki/Sleep_Talk_(move)');
INSERT INTO PM_MOVE VALUES  (215,'Heal Bell','http://bulbapedia.bulbagarden.net/wiki/Heal_Bell_(move)');
INSERT INTO PM_MOVE VALUES  (216,'Return','http://bulbapedia.bulbagarden.net/wiki/Return_(move)');
INSERT INTO PM_MOVE VALUES  (217,'Present','http://bulbapedia.bulbagarden.net/wiki/Present_(move)');
INSERT INTO PM_MOVE VALUES  (218,'Frustration','http://bulbapedia.bulbagarden.net/wiki/Frustration_(move)');
INSERT INTO PM_MOVE VALUES  (219,'Safeguard','http://bulbapedia.bulbagarden.net/wiki/Safeguard_(move)');
INSERT INTO PM_MOVE VALUES  (220,'Pain Split','http://bulbapedia.bulbagarden.net/wiki/Pain_Split_(move)');
INSERT INTO PM_MOVE VALUES  (221,'Sacred Fire','http://bulbapedia.bulbagarden.net/wiki/Sacred_Fire_(move)');
INSERT INTO PM_MOVE VALUES  (222,'Magnitude','http://bulbapedia.bulbagarden.net/wiki/Magnitude_(move)');
INSERT INTO PM_MOVE VALUES  (223,'DynamicPunch','http://bulbapedia.bulbagarden.net/wiki/DynamicPunch_(move)');
INSERT INTO PM_MOVE VALUES  (224,'Megahorn','http://bulbapedia.bulbagarden.net/wiki/Megahorn_(move)');
INSERT INTO PM_MOVE VALUES  (225,'DragonBreath','http://bulbapedia.bulbagarden.net/wiki/DragonBreath_(move)');
INSERT INTO PM_MOVE VALUES  (226,'Baton Pass','http://bulbapedia.bulbagarden.net/wiki/Baton_Pass_(move)');
INSERT INTO PM_MOVE VALUES  (227,'Encore','');
INSERT INTO PM_MOVE VALUES  (228,'Pursuit','http://bulbapedia.bulbagarden.net/wiki/Pursuit_(move)');
INSERT INTO PM_MOVE VALUES  (229,'Rapid Spin','http://bulbapedia.bulbagarden.net/wiki/Rapid_Spin_(move)');
INSERT INTO PM_MOVE VALUES  (230,'Sweet Scent','http://bulbapedia.bulbagarden.net/wiki/Sweet_Scent_(move)');
INSERT INTO PM_MOVE VALUES  (231,'Iron Tail','http://bulbapedia.bulbagarden.net/wiki/Iron_Tail_(move)');
INSERT INTO PM_MOVE VALUES  (232,'Metal Claw','http://bulbapedia.bulbagarden.net/wiki/Metal_Claw_(move)');
INSERT INTO PM_MOVE VALUES  (233,'Vital Throw','http://bulbapedia.bulbagarden.net/wiki/Vital_Throw_(move)');
INSERT INTO PM_MOVE VALUES  (234,'Morning Sun','http://bulbapedia.bulbagarden.net/wiki/Morning_Sun_(move)');
INSERT INTO PM_MOVE VALUES  (235,'Synthesis','http://bulbapedia.bulbagarden.net/wiki/Synthesis_(move)');
INSERT INTO PM_MOVE VALUES  (236,'Moonlight','http://bulbapedia.bulbagarden.net/wiki/Moonlight_(move)');
INSERT INTO PM_MOVE VALUES  (237,'Hidden Power','http://bulbapedia.bulbagarden.net/wiki/Hidden_Power_(move)');
INSERT INTO PM_MOVE VALUES  (238,'Cross Chop','http://bulbapedia.bulbagarden.net/wiki/Cross_Chop_(move)');
INSERT INTO PM_MOVE VALUES  (239,'Twister','http://bulbapedia.bulbagarden.net/wiki/Twister_(move)');
INSERT INTO PM_MOVE VALUES  (240,'Rain Dance','http://bulbapedia.bulbagarden.net/wiki/Rain_Dance_(move)');
INSERT INTO PM_MOVE VALUES  (241,'Sunny Day','http://bulbapedia.bulbagarden.net/wiki/Sunny_Day_(move)');
INSERT INTO PM_MOVE VALUES  (242,'Crunch','http://bulbapedia.bulbagarden.net/wiki/Crunch_(move)');
INSERT INTO PM_MOVE VALUES  (243,'Mirror Coat','http://bulbapedia.bulbagarden.net/wiki/Mirror_Coat_(move)');
INSERT INTO PM_MOVE VALUES  (244,'Psych Up','http://bulbapedia.bulbagarden.net/wiki/Psych_Up_(move)');
INSERT INTO PM_MOVE VALUES  (245,'ExtremeSpeed','http://bulbapedia.bulbagarden.net/wiki/ExtremeSpeed_(move)');
INSERT INTO PM_MOVE VALUES  (246,'AncientPower','http://bulbapedia.bulbagarden.net/wiki/AncientPower_(move)');
INSERT INTO PM_MOVE VALUES  (247,'Shadow Ball','http://bulbapedia.bulbagarden.net/wiki/Shadow_Ball_(move)');
INSERT INTO PM_MOVE VALUES  (248,'Future Sight','http://bulbapedia.bulbagarden.net/wiki/Future_Sight_(move)');
INSERT INTO PM_MOVE VALUES  (249,'Rock Smash','http://bulbapedia.bulbagarden.net/wiki/Rock_Smash_(move)');
INSERT INTO PM_MOVE VALUES  (250,'Whirlpool','http://bulbapedia.bulbagarden.net/wiki/Whirlpool_(move)');
INSERT INTO PM_MOVE VALUES  (251,'Beat Up','http://bulbapedia.bulbagarden.net/wiki/Beat_Up_(move)');
INSERT INTO PM_MOVE VALUES  (252,'Fake Out','http://bulbapedia.bulbagarden.net/wiki/Fake_Out_(move)');
INSERT INTO PM_MOVE VALUES  (253,'Uproar','http://bulbapedia.bulbagarden.net/wiki/Uproar_(move)');
INSERT INTO PM_MOVE VALUES  (254,'Stockpile','http://bulbapedia.bulbagarden.net/wiki/Stockpile_(move)');
INSERT INTO PM_MOVE VALUES  (255,'Spit Up','http://bulbapedia.bulbagarden.net/wiki/Spit_Up_(move)');
INSERT INTO PM_MOVE VALUES  (256,'Swallow','http://bulbapedia.bulbagarden.net/wiki/Swallow_(move)');
INSERT INTO PM_MOVE VALUES  (257,'Heat Wave','http://bulbapedia.bulbagarden.net/wiki/Heat_Wave_(move)');
INSERT INTO PM_MOVE VALUES  (258,'Hail','http://bulbapedia.bulbagarden.net/wiki/Hail_(move)');
INSERT INTO PM_MOVE VALUES  (259,'Torment','http://bulbapedia.bulbagarden.net/wiki/Torment_(move)');
INSERT INTO PM_MOVE VALUES  (260,'Flatter','http://bulbapedia.bulbagarden.net/wiki/Flatter_(move)');
INSERT INTO PM_MOVE VALUES  (261,'Will-O-Wisp','http://bulbapedia.bulbagarden.net/wiki/Will-O-Wisp_(move)');
INSERT INTO PM_MOVE VALUES  (262,'Memento','http://bulbapedia.bulbagarden.net/wiki/Memento_(move)');
INSERT INTO PM_MOVE VALUES  (263,'Facade','http://bulbapedia.bulbagarden.net/wiki/Facade_(move)');
INSERT INTO PM_MOVE VALUES  (264,'Focus Punch','http://bulbapedia.bulbagarden.net/wiki/Focus_Punch_(move)');
INSERT INTO PM_MOVE VALUES  (265,'SmellingSalt','http://bulbapedia.bulbagarden.net/wiki/SmellingSalt_(move)');
INSERT INTO PM_MOVE VALUES  (266,'Follow Me','http://bulbapedia.bulbagarden.net/wiki/Follow_Me_(move)');
INSERT INTO PM_MOVE VALUES  (267,'Nature Power','http://bulbapedia.bulbagarden.net/wiki/Nature_Power_(move)');
INSERT INTO PM_MOVE VALUES  (268,'Charge','http://bulbapedia.bulbagarden.net/wiki/Charge_(move)');
INSERT INTO PM_MOVE VALUES  (269,'Taunt','http://bulbapedia.bulbagarden.net/wiki/Taunt_(move)');
INSERT INTO PM_MOVE VALUES  (270,'Helping Hand','http://bulbapedia.bulbagarden.net/wiki/Helping_Hand_(move)');
INSERT INTO PM_MOVE VALUES  (271,'Trick','http://bulbapedia.bulbagarden.net/wiki/Trick_(move)');
INSERT INTO PM_MOVE VALUES  (272,'Role Play','http://bulbapedia.bulbagarden.net/wiki/Role_Play_(move)');
INSERT INTO PM_MOVE VALUES  (273,'Wish','http://bulbapedia.bulbagarden.net/wiki/Wish_(move)');
INSERT INTO PM_MOVE VALUES  (274,'Assist','http://bulbapedia.bulbagarden.net/wiki/Assist_(move)');
INSERT INTO PM_MOVE VALUES  (275,'Ingrain','http://bulbapedia.bulbagarden.net/wiki/Ingrain_(move)');
INSERT INTO PM_MOVE VALUES  (276,'Superpower','http://bulbapedia.bulbagarden.net/wiki/Superpower_(move)');
INSERT INTO PM_MOVE VALUES  (277,'Magic Coat','http://bulbapedia.bulbagarden.net/wiki/Magic_Coat_(move)');
INSERT INTO PM_MOVE VALUES  (278,'Recycle','http://bulbapedia.bulbagarden.net/wiki/Recycle_(move)');
INSERT INTO PM_MOVE VALUES  (279,'Revenge','http://bulbapedia.bulbagarden.net/wiki/Revenge_(move)');
INSERT INTO PM_MOVE VALUES  (280,'Brick Break','http://bulbapedia.bulbagarden.net/wiki/Brick_Break_(move)');
INSERT INTO PM_MOVE VALUES  (281,'Yawn','http://bulbapedia.bulbagarden.net/wiki/Yawn_(move)');
INSERT INTO PM_MOVE VALUES  (282,'Knock Off','http://bulbapedia.bulbagarden.net/wiki/Knock_Off_(move)');
INSERT INTO PM_MOVE VALUES  (283,'Endeavor','http://bulbapedia.bulbagarden.net/wiki/Endeavor_(move)');
INSERT INTO PM_MOVE VALUES  (284,'Eruption','http://bulbapedia.bulbagarden.net/wiki/Eruption_(move)');
INSERT INTO PM_MOVE VALUES  (285,'Skill Swap','http://bulbapedia.bulbagarden.net/wiki/Skill_Swap_(move)');
INSERT INTO PM_MOVE VALUES  (286,'Imprison','http://bulbapedia.bulbagarden.net/wiki/Imprison_(move)');
INSERT INTO PM_MOVE VALUES  (287,'Refresh','http://bulbapedia.bulbagarden.net/wiki/Refresh_(move)');
INSERT INTO PM_MOVE VALUES  (288,'Grudge','http://bulbapedia.bulbagarden.net/wiki/Grudge_(move)');
INSERT INTO PM_MOVE VALUES  (289,'Snatch','http://bulbapedia.bulbagarden.net/wiki/Snatch_(move)');
INSERT INTO PM_MOVE VALUES  (290,'Secret Power','http://bulbapedia.bulbagarden.net/wiki/Secret_Power_(move)');
INSERT INTO PM_MOVE VALUES  (291,'Dive','http://bulbapedia.bulbagarden.net/wiki/Dive_(move)');
INSERT INTO PM_MOVE VALUES  (292,'Arm Thrust','http://bulbapedia.bulbagarden.net/wiki/Arm_Thrust_(move)');
INSERT INTO PM_MOVE VALUES  (293,'Camouflage','http://bulbapedia.bulbagarden.net/wiki/Camouflage_(move)');
INSERT INTO PM_MOVE VALUES  (294,'Tail Glow','http://bulbapedia.bulbagarden.net/wiki/Tail_Glow_(move)');
INSERT INTO PM_MOVE VALUES  (295,'Luster Purge','http://bulbapedia.bulbagarden.net/wiki/Luster_Purge_(move)');
INSERT INTO PM_MOVE VALUES  (296,'Mist Ball','http://bulbapedia.bulbagarden.net/wiki/Mist_Ball_(move)');
INSERT INTO PM_MOVE VALUES  (297,'FeatherDance','http://bulbapedia.bulbagarden.net/wiki/FeatherDance_(move)');
INSERT INTO PM_MOVE VALUES  (298,'Teeter Dance','http://bulbapedia.bulbagarden.net/wiki/Teeter_Dance_(move)');
INSERT INTO PM_MOVE VALUES  (299,'Blaze Kick','http://bulbapedia.bulbagarden.net/wiki/Blaze_Kick_(move)');
INSERT INTO PM_MOVE VALUES  (300,'Mud Sport','http://bulbapedia.bulbagarden.net/wiki/Mud_Sport_(move)');
INSERT INTO PM_MOVE VALUES  (301,'Ice Ball','http://bulbapedia.bulbagarden.net/wiki/Ice_Ball_(move)');
INSERT INTO PM_MOVE VALUES  (302,'Needle Arm','http://bulbapedia.bulbagarden.net/wiki/Needle_Arm_(move)');
INSERT INTO PM_MOVE VALUES  (303,'Slack Off','http://bulbapedia.bulbagarden.net/wiki/Slack_Off_(move)');
INSERT INTO PM_MOVE VALUES  (304,'Hyper Voice','http://bulbapedia.bulbagarden.net/wiki/Hyper_Voice_(move)');
INSERT INTO PM_MOVE VALUES  (305,'Poison Fang','http://bulbapedia.bulbagarden.net/wiki/Poison_Fang_(move)');
INSERT INTO PM_MOVE VALUES  (306,'Crush Claw','http://bulbapedia.bulbagarden.net/wiki/Crush_Claw_(move)');
INSERT INTO PM_MOVE VALUES  (307,'Blast Burn','http://bulbapedia.bulbagarden.net/wiki/Blast_Burn_(move)');
INSERT INTO PM_MOVE VALUES  (308,'Hydro Cannon','http://bulbapedia.bulbagarden.net/wiki/Hydro_Cannon_(move)');
INSERT INTO PM_MOVE VALUES  (309,'Meteor Mash','http://bulbapedia.bulbagarden.net/wiki/Meteor_Mash_(move)');
INSERT INTO PM_MOVE VALUES  (310,'Astonish','http://bulbapedia.bulbagarden.net/wiki/Astonish_(move)');
INSERT INTO PM_MOVE VALUES  (311,'Weather Ball','http://bulbapedia.bulbagarden.net/wiki/Weather_Ball_(move)');
INSERT INTO PM_MOVE VALUES  (312,'Aromatherapy','http://bulbapedia.bulbagarden.net/wiki/Aromatherapy_(move)');
INSERT INTO PM_MOVE VALUES  (313,'Fake Tears','http://bulbapedia.bulbagarden.net/wiki/Fake_Tears_(move)');
INSERT INTO PM_MOVE VALUES  (314,'Air Cutter','http://bulbapedia.bulbagarden.net/wiki/Air_Cutter_(move)');
INSERT INTO PM_MOVE VALUES  (315,'Overheat','http://bulbapedia.bulbagarden.net/wiki/Overheat_(move)');
INSERT INTO PM_MOVE VALUES  (316,'Odor Sleuth','http://bulbapedia.bulbagarden.net/wiki/Odor_Sleuth_(move)');
INSERT INTO PM_MOVE VALUES  (317,'Rock Tomb','http://bulbapedia.bulbagarden.net/wiki/Rock_Tomb_(move)');
INSERT INTO PM_MOVE VALUES  (318,'Silver Wind','http://bulbapedia.bulbagarden.net/wiki/Silver_Wind_(move)');
INSERT INTO PM_MOVE VALUES  (319,'Metal Sound','http://bulbapedia.bulbagarden.net/wiki/Metal_Sound_(move)');
INSERT INTO PM_MOVE VALUES  (320,'GrassWhistle','http://bulbapedia.bulbagarden.net/wiki/GrassWhistle_(move)');
INSERT INTO PM_MOVE VALUES  (321,'Tickle','http://bulbapedia.bulbagarden.net/wiki/Tickle_(move)');
INSERT INTO PM_MOVE VALUES  (322,'Cosmic Power','http://bulbapedia.bulbagarden.net/wiki/Cosmic_Power_(move)');
INSERT INTO PM_MOVE VALUES  (323,'Water Spout','http://bulbapedia.bulbagarden.net/wiki/Water_Spout_(move)');
INSERT INTO PM_MOVE VALUES  (324,'Signal Beam','http://bulbapedia.bulbagarden.net/wiki/Signal_Beam_(move)');
INSERT INTO PM_MOVE VALUES  (325,'Shadow Punch','http://bulbapedia.bulbagarden.net/wiki/Shadow_Punch_(move)');
INSERT INTO PM_MOVE VALUES  (326,'Extrasensory','http://bulbapedia.bulbagarden.net/wiki/Extrasensory_(move)');
INSERT INTO PM_MOVE VALUES  (327,'Sky Uppercut','http://bulbapedia.bulbagarden.net/wiki/Sky_Uppercut_(move)');
INSERT INTO PM_MOVE VALUES  (328,'Sand Tomb','http://bulbapedia.bulbagarden.net/wiki/Sand_Tomb_(move)');
INSERT INTO PM_MOVE VALUES  (329,'Sheer Cold','http://bulbapedia.bulbagarden.net/wiki/Sheer_Cold_(move)');
INSERT INTO PM_MOVE VALUES  (330,'Muddy Water','http://bulbapedia.bulbagarden.net/wiki/Muddy_Water_(move)');
INSERT INTO PM_MOVE VALUES  (331,'Bullet Seed','http://bulbapedia.bulbagarden.net/wiki/Bullet_Seed_(move)');
INSERT INTO PM_MOVE VALUES  (332,'Aerial Ace','http://bulbapedia.bulbagarden.net/wiki/Aerial_Ace_(move)');
INSERT INTO PM_MOVE VALUES  (333,'Icicle Spear','http://bulbapedia.bulbagarden.net/wiki/Icicle_Spear_(move)');
INSERT INTO PM_MOVE VALUES  (334,'Iron Defense','http://bulbapedia.bulbagarden.net/wiki/Iron_Defense_(move)');
INSERT INTO PM_MOVE VALUES  (335,'Block','http://bulbapedia.bulbagarden.net/wiki/Block_(move)');
INSERT INTO PM_MOVE VALUES  (336,'Howl','http://bulbapedia.bulbagarden.net/wiki/Howl_(move)');
INSERT INTO PM_MOVE VALUES  (337,'Dragon Claw','http://bulbapedia.bulbagarden.net/wiki/Dragon_Claw_(move)');
INSERT INTO PM_MOVE VALUES  (338,'Frenzy Plant','http://bulbapedia.bulbagarden.net/wiki/Frenzy_Plant_(move)');
INSERT INTO PM_MOVE VALUES  (339,'Bulk Up','http://bulbapedia.bulbagarden.net/wiki/Bulk_Up_(move)');
INSERT INTO PM_MOVE VALUES  (340,'Bounce','http://bulbapedia.bulbagarden.net/wiki/Bounce_(move)');
INSERT INTO PM_MOVE VALUES  (341,'Mud Shot','http://bulbapedia.bulbagarden.net/wiki/Mud_Shot_(move)');
INSERT INTO PM_MOVE VALUES  (342,'Poison Tail','http://bulbapedia.bulbagarden.net/wiki/Poison_Tail_(move)');
INSERT INTO PM_MOVE VALUES  (343,'Covet','http://bulbapedia.bulbagarden.net/wiki/Covet_(move)');
INSERT INTO PM_MOVE VALUES  (344,'Volt Tackle','http://bulbapedia.bulbagarden.net/wiki/Volt_Tackle_(move)');
INSERT INTO PM_MOVE VALUES  (345,'Magical Leaf','http://bulbapedia.bulbagarden.net/wiki/Magical_Leaf_(move)');
INSERT INTO PM_MOVE VALUES  (346,'Water Sport','http://bulbapedia.bulbagarden.net/wiki/Water_Sport_(move)');
INSERT INTO PM_MOVE VALUES  (347,'Calm Mind','http://bulbapedia.bulbagarden.net/wiki/Calm_Mind_(move)');
INSERT INTO PM_MOVE VALUES  (348,'Leaf Blade','http://bulbapedia.bulbagarden.net/wiki/Leaf_Blade_(move)');
INSERT INTO PM_MOVE VALUES  (349,'Dragon Dance','http://bulbapedia.bulbagarden.net/wiki/Dragon_Dance_(move)');
INSERT INTO PM_MOVE VALUES  (350,'Rock Blast','http://bulbapedia.bulbagarden.net/wiki/Rock_Blast_(move)');
INSERT INTO PM_MOVE VALUES  (351,'Shock Wave','http://bulbapedia.bulbagarden.net/wiki/Shock_Wave_(move)');
INSERT INTO PM_MOVE VALUES  (352,'Water Pulse','http://bulbapedia.bulbagarden.net/wiki/Water_Pulse_(move)');
INSERT INTO PM_MOVE VALUES  (353,'Doom Desire','http://bulbapedia.bulbagarden.net/wiki/Doom_Desire_(move)');
INSERT INTO PM_MOVE VALUES  (354,'Psycho Boost','http://bulbapedia.bulbagarden.net/wiki/Psycho_Boost_(move)');
INSERT INTO PM_MOVE VALUES  (355,'Roost','http://bulbapedia.bulbagarden.net/wiki/Roost_(move)');
INSERT INTO PM_MOVE VALUES  (356,'Gravity','http://bulbapedia.bulbagarden.net/wiki/Gravity_(move)');
INSERT INTO PM_MOVE VALUES  (357,'Miracle Eye','http://bulbapedia.bulbagarden.net/wiki/Miracle_Eye_(move)');
INSERT INTO PM_MOVE VALUES  (358,'Wake-Up Slap','http://bulbapedia.bulbagarden.net/wiki/Wake-Up_Slap_(move)');
INSERT INTO PM_MOVE VALUES  (359,'Hammer Arm','http://bulbapedia.bulbagarden.net/wiki/Hammer_Arm_(move)');
INSERT INTO PM_MOVE VALUES  (360,'Gyro Ball','http://bulbapedia.bulbagarden.net/wiki/Gyro_Ball_(move)');
INSERT INTO PM_MOVE VALUES  (361,'Healing Wish','http://bulbapedia.bulbagarden.net/wiki/Healing_Wish_(move)');
INSERT INTO PM_MOVE VALUES  (362,'Brine','http://bulbapedia.bulbagarden.net/wiki/Brine_(move)');
INSERT INTO PM_MOVE VALUES  (363,'Natural Gift','http://bulbapedia.bulbagarden.net/wiki/Natural_Gift_(move)');
INSERT INTO PM_MOVE VALUES  (364,'Feint','http://bulbapedia.bulbagarden.net/wiki/Feint_(move)');
INSERT INTO PM_MOVE VALUES  (365,'Pluck','http://bulbapedia.bulbagarden.net/wiki/Pluck_(move)');
INSERT INTO PM_MOVE VALUES  (366,'Tailwind','http://bulbapedia.bulbagarden.net/wiki/Tailwind_(move)');
INSERT INTO PM_MOVE VALUES  (367,'Acupressure','http://bulbapedia.bulbagarden.net/wiki/Acupressure_(move)');
INSERT INTO PM_MOVE VALUES  (368,'Metal Burst','http://bulbapedia.bulbagarden.net/wiki/Metal_Burst_(move)');
INSERT INTO PM_MOVE VALUES  (369,'U-turn','http://bulbapedia.bulbagarden.net/wiki/U-turn_(move)');
INSERT INTO PM_MOVE VALUES  (370,'Close Combat','http://bulbapedia.bulbagarden.net/wiki/Close_Combat_(move)');
INSERT INTO PM_MOVE VALUES  (371,'Payback','http://bulbapedia.bulbagarden.net/wiki/Payback_(move)');
INSERT INTO PM_MOVE VALUES  (372,'Assurance','http://bulbapedia.bulbagarden.net/wiki/Assurance_(move)');
INSERT INTO PM_MOVE VALUES  (373,'Embargo','http://bulbapedia.bulbagarden.net/wiki/Embargo_(move)');
INSERT INTO PM_MOVE VALUES  (374,'Fling','http://bulbapedia.bulbagarden.net/wiki/Fling_(move)');
INSERT INTO PM_MOVE VALUES  (375,'Psycho Shift','http://bulbapedia.bulbagarden.net/wiki/Psycho_Shift_(move)');
INSERT INTO PM_MOVE VALUES  (376,'Trump Card','http://bulbapedia.bulbagarden.net/wiki/Trump_Card_(move)');
INSERT INTO PM_MOVE VALUES  (377,'Heal Block','http://bulbapedia.bulbagarden.net/wiki/Heal_Block_(move)');
INSERT INTO PM_MOVE VALUES  (378,'Wring Out','http://bulbapedia.bulbagarden.net/wiki/Wring_Out_(move)');
INSERT INTO PM_MOVE VALUES  (379,'Power Trick','http://bulbapedia.bulbagarden.net/wiki/Power_Trick_(move)');
INSERT INTO PM_MOVE VALUES  (380,'Gastro Acid','http://bulbapedia.bulbagarden.net/wiki/Gastro_Acid_(move)');
INSERT INTO PM_MOVE VALUES  (381,'Lucky Chant','http://bulbapedia.bulbagarden.net/wiki/Lucky_Chant_(move)');
INSERT INTO PM_MOVE VALUES  (382,'Me First','http://bulbapedia.bulbagarden.net/wiki/Me_First_(move)');
INSERT INTO PM_MOVE VALUES  (383,'Copycat','http://bulbapedia.bulbagarden.net/wiki/Copycat_(move)');
INSERT INTO PM_MOVE VALUES  (384,'Power Swap','http://bulbapedia.bulbagarden.net/wiki/Power_Swap_(move)');
INSERT INTO PM_MOVE VALUES  (385,'Guard Swap','http://bulbapedia.bulbagarden.net/wiki/Guard_Swap_(move)');
INSERT INTO PM_MOVE VALUES  (386,'Punishment','http://bulbapedia.bulbagarden.net/wiki/Punishment_(move)');
INSERT INTO PM_MOVE VALUES  (387,'Last Resort','http://bulbapedia.bulbagarden.net/wiki/Last_Resort_(move)');
INSERT INTO PM_MOVE VALUES  (388,'Worry Seed','http://bulbapedia.bulbagarden.net/wiki/Worry_Seed_(move)');
INSERT INTO PM_MOVE VALUES  (389,'Sucker Punch','http://bulbapedia.bulbagarden.net/wiki/Sucker_Punch_(move)');
INSERT INTO PM_MOVE VALUES  (390,'Toxic Spikes','http://bulbapedia.bulbagarden.net/wiki/Toxic_Spikes_(move)');
INSERT INTO PM_MOVE VALUES  (391,'Heart Swap','http://bulbapedia.bulbagarden.net/wiki/Heart_Swap_(move)');
INSERT INTO PM_MOVE VALUES  (392,'Aqua Ring','http://bulbapedia.bulbagarden.net/wiki/Aqua_Ring_(move)');
INSERT INTO PM_MOVE VALUES  (393,'Magnet Rise','http://bulbapedia.bulbagarden.net/wiki/Magnet_Rise_(move)');
INSERT INTO PM_MOVE VALUES  (394,'Flare Blitz','http://bulbapedia.bulbagarden.net/wiki/Flare_Blitz_(move)');
INSERT INTO PM_MOVE VALUES  (395,'Force Palm','http://bulbapedia.bulbagarden.net/wiki/Force_Palm_(move)');
INSERT INTO PM_MOVE VALUES  (396,'Aura Sphere','http://bulbapedia.bulbagarden.net/wiki/Aura_Sphere_(move)');
INSERT INTO PM_MOVE VALUES  (397,'Rock Polish','http://bulbapedia.bulbagarden.net/wiki/Rock_Polish_(move)');
INSERT INTO PM_MOVE VALUES  (398,'Poison Jab','http://bulbapedia.bulbagarden.net/wiki/Poison_Jab_(move)');
INSERT INTO PM_MOVE VALUES  (399,'Dark Pulse','http://bulbapedia.bulbagarden.net/wiki/Dark_Pulse_(move)');
INSERT INTO PM_MOVE VALUES  (400,'Night Slash','http://bulbapedia.bulbagarden.net/wiki/Night_Slash_(move)');
INSERT INTO PM_MOVE VALUES  (401,'Aqua Tail','http://bulbapedia.bulbagarden.net/wiki/Aqua_Tail_(move)');
INSERT INTO PM_MOVE VALUES  (402,'Seed Bomb','http://bulbapedia.bulbagarden.net/wiki/Seed_Bomb_(move)');
INSERT INTO PM_MOVE VALUES  (403,'Air Slash','http://bulbapedia.bulbagarden.net/wiki/Air_Slash_(move)');
INSERT INTO PM_MOVE VALUES  (404,'X-Scissor','http://bulbapedia.bulbagarden.net/wiki/X-Scissor_(move)');
INSERT INTO PM_MOVE VALUES  (405,'Bug Buzz','http://bulbapedia.bulbagarden.net/wiki/Bug_Buzz_(move)');
INSERT INTO PM_MOVE VALUES  (406,'Dragon Pulse','http://bulbapedia.bulbagarden.net/wiki/Dragon_Pulse_(move)');
INSERT INTO PM_MOVE VALUES  (407,'Dragon Rush','http://bulbapedia.bulbagarden.net/wiki/Dragon_Rush_(move)');
INSERT INTO PM_MOVE VALUES  (408,'Power Gem','http://bulbapedia.bulbagarden.net/wiki/Power_Gem_(move)');
INSERT INTO PM_MOVE VALUES  (409,'Drain Punch','http://bulbapedia.bulbagarden.net/wiki/Drain_Punch_(move)');
INSERT INTO PM_MOVE VALUES  (410,'Vacuum Wave','http://bulbapedia.bulbagarden.net/wiki/Vacuum_Wave_(move)');
INSERT INTO PM_MOVE VALUES  (411,'Focus Blast','http://bulbapedia.bulbagarden.net/wiki/Focus_Blast_(move)');
INSERT INTO PM_MOVE VALUES  (412,'Energy Ball','http://bulbapedia.bulbagarden.net/wiki/Energy_Ball_(move)');
INSERT INTO PM_MOVE VALUES  (413,'Brave Bird','http://bulbapedia.bulbagarden.net/wiki/Brave_Bird_(move)');
INSERT INTO PM_MOVE VALUES  (414,'Earth Power','http://bulbapedia.bulbagarden.net/wiki/Earth_Power_(move)');
INSERT INTO PM_MOVE VALUES  (415,'Switcheroo','http://bulbapedia.bulbagarden.net/wiki/Switcheroo_(move)');
INSERT INTO PM_MOVE VALUES  (416,'Giga Impact','http://bulbapedia.bulbagarden.net/wiki/Giga_Impact_(move)');
INSERT INTO PM_MOVE VALUES  (417,'Nasty Plot','http://bulbapedia.bulbagarden.net/wiki/Nasty_Plot_(move)');
INSERT INTO PM_MOVE VALUES  (418,'Bullet Punch','http://bulbapedia.bulbagarden.net/wiki/Bullet_Punch_(move)');
INSERT INTO PM_MOVE VALUES  (419,'Avalanche','http://bulbapedia.bulbagarden.net/wiki/Avalanche_(move)');
INSERT INTO PM_MOVE VALUES  (420,'Ice Shard','http://bulbapedia.bulbagarden.net/wiki/Ice_Shard_(move)');
INSERT INTO PM_MOVE VALUES  (421,'Shadow Claw','http://bulbapedia.bulbagarden.net/wiki/Shadow_Claw_(move)');
INSERT INTO PM_MOVE VALUES  (422,'Thunder Fang','http://bulbapedia.bulbagarden.net/wiki/Thunder_Fang_(move)');
INSERT INTO PM_MOVE VALUES  (423,'Ice Fang','http://bulbapedia.bulbagarden.net/wiki/Ice_Fang_(move)');
INSERT INTO PM_MOVE VALUES  (424,'Fire Fang','http://bulbapedia.bulbagarden.net/wiki/Fire_Fang_(move)');
INSERT INTO PM_MOVE VALUES  (425,'Shadow Sneak','http://bulbapedia.bulbagarden.net/wiki/Shadow_Sneak_(move)');
INSERT INTO PM_MOVE VALUES  (426,'Mud Bomb','http://bulbapedia.bulbagarden.net/wiki/Mud_Bomb_(move)');
INSERT INTO PM_MOVE VALUES  (427,'Psycho Cut','http://bulbapedia.bulbagarden.net/wiki/Psycho_Cut_(move)');
INSERT INTO PM_MOVE VALUES  (428,'Zen Headbutt','http://bulbapedia.bulbagarden.net/wiki/Zen_Headbutt_(move)');
INSERT INTO PM_MOVE VALUES  (429,'Mirror Shot','http://bulbapedia.bulbagarden.net/wiki/Mirror_Shot_(move)');
INSERT INTO PM_MOVE VALUES  (430,'Flash Cannon','http://bulbapedia.bulbagarden.net/wiki/Flash_Cannon_(move)');
INSERT INTO PM_MOVE VALUES  (431,'Rock Climb','http://bulbapedia.bulbagarden.net/wiki/Rock_Climb_(move)');
INSERT INTO PM_MOVE VALUES  (432,'Defog','http://bulbapedia.bulbagarden.net/wiki/Defog_(move)');
INSERT INTO PM_MOVE VALUES  (433,'Trick Room','http://bulbapedia.bulbagarden.net/wiki/Trick_Room_(move)');
INSERT INTO PM_MOVE VALUES  (434,'Draco Meteor','http://bulbapedia.bulbagarden.net/wiki/Draco_Meteor_(move)');
INSERT INTO PM_MOVE VALUES  (435,'Discharge','http://bulbapedia.bulbagarden.net/wiki/Discharge_(move)');
INSERT INTO PM_MOVE VALUES  (436,'Lava Plume','http://bulbapedia.bulbagarden.net/wiki/Lava_Plume_(move)');
INSERT INTO PM_MOVE VALUES  (437,'Leaf Storm','http://bulbapedia.bulbagarden.net/wiki/Leaf_Storm_(move)');
INSERT INTO PM_MOVE VALUES  (438,'Power Whip','http://bulbapedia.bulbagarden.net/wiki/Power_Whip_(move)');
INSERT INTO PM_MOVE VALUES  (439,'Rock Wrecker','http://bulbapedia.bulbagarden.net/wiki/Rock_Wrecker_(move)');
INSERT INTO PM_MOVE VALUES  (440,'Cross Poison','http://bulbapedia.bulbagarden.net/wiki/Cross_Poison_(move)');
INSERT INTO PM_MOVE VALUES  (441,'Gunk Shot','http://bulbapedia.bulbagarden.net/wiki/Gunk_Shot_(move)');
INSERT INTO PM_MOVE VALUES  (442,'Iron Head','http://bulbapedia.bulbagarden.net/wiki/Iron_Head_(move)');
INSERT INTO PM_MOVE VALUES  (443,'Magnet Bomb','http://bulbapedia.bulbagarden.net/wiki/Magnet_Bomb_(move)');
INSERT INTO PM_MOVE VALUES  (444,'Stone Edge','http://bulbapedia.bulbagarden.net/wiki/Stone_Edge_(move)');
INSERT INTO PM_MOVE VALUES  (445,'Captivate','http://bulbapedia.bulbagarden.net/wiki/Captivate_(move)');
INSERT INTO PM_MOVE VALUES  (446,'Stealth Rock','http://bulbapedia.bulbagarden.net/wiki/Stealth_Rock_(move)');
INSERT INTO PM_MOVE VALUES  (447,'Grass Knot','http://bulbapedia.bulbagarden.net/wiki/Grass_Knot_(move)');
INSERT INTO PM_MOVE VALUES  (448,'Chatter','http://bulbapedia.bulbagarden.net/wiki/Chatter_(move)');
INSERT INTO PM_MOVE VALUES  (449,'Judgment','http://bulbapedia.bulbagarden.net/wiki/Judgment_(move)');
INSERT INTO PM_MOVE VALUES  (450,'Bug Bite','http://bulbapedia.bulbagarden.net/wiki/Bug_Bite_(move)');
INSERT INTO PM_MOVE VALUES  (451,'Charge Beam','http://bulbapedia.bulbagarden.net/wiki/Charge_Beam_(move)');
INSERT INTO PM_MOVE VALUES  (452,'Wood Hammer','http://bulbapedia.bulbagarden.net/wiki/Wood_Hammer_(move)');
INSERT INTO PM_MOVE VALUES  (453,'Aqua Jet','http://bulbapedia.bulbagarden.net/wiki/Aqua_Jet_(move)');
INSERT INTO PM_MOVE VALUES  (454,'Attack Order','http://bulbapedia.bulbagarden.net/wiki/Attack_Order_(move)');
INSERT INTO PM_MOVE VALUES  (455,'Defend Order','http://bulbapedia.bulbagarden.net/wiki/Defend_Order_(move)');
INSERT INTO PM_MOVE VALUES  (456,'Heal Order','http://bulbapedia.bulbagarden.net/wiki/Heal_Order_(move)');
INSERT INTO PM_MOVE VALUES  (457,'Head Smash','http://bulbapedia.bulbagarden.net/wiki/Head_Smash_(move)');
INSERT INTO PM_MOVE VALUES  (458,'Double Hit','http://bulbapedia.bulbagarden.net/wiki/Double_Hit_(move)');
INSERT INTO PM_MOVE VALUES  (459,'Roar of Time','http://bulbapedia.bulbagarden.net/wiki/Roar_of_Time_(move)');
INSERT INTO PM_MOVE VALUES  (460,'Spacial Rend','http://bulbapedia.bulbagarden.net/wiki/Spacial_Rend_(move)');
INSERT INTO PM_MOVE VALUES  (461,'Lunar Dance','http://bulbapedia.bulbagarden.net/wiki/Lunar_Dance_(move)');
INSERT INTO PM_MOVE VALUES  (462,'Crush Grip','http://bulbapedia.bulbagarden.net/wiki/Crush_Grip_(move)');
INSERT INTO PM_MOVE VALUES  (463,'Magma Storm','http://bulbapedia.bulbagarden.net/wiki/Magma_Storm_(move)');
INSERT INTO PM_MOVE VALUES  (464,'Dark Void','http://bulbapedia.bulbagarden.net/wiki/Dark_Void_(move)');
INSERT INTO PM_MOVE VALUES  (465,'Seed Flare','http://bulbapedia.bulbagarden.net/wiki/Seed_Flare_(move)');
INSERT INTO PM_MOVE VALUES  (466,'Ominous Wind','http://bulbapedia.bulbagarden.net/wiki/Ominous_Wind_(move)');
INSERT INTO PM_MOVE VALUES  (467,'Shadow Force','http://bulbapedia.bulbagarden.net/wiki/Shadow_Force_(move)');
INSERT INTO PM_MOVE VALUES  (468,'Hone Claws','http://bulbapedia.bulbagarden.net/wiki/Hone_Claws_(move)');
INSERT INTO PM_MOVE VALUES  (469,'Wide Guard','http://bulbapedia.bulbagarden.net/wiki/Wide_Guard_(move)');
INSERT INTO PM_MOVE VALUES  (470,'Guard Split','http://bulbapedia.bulbagarden.net/wiki/Guard_Split_(move)');
INSERT INTO PM_MOVE VALUES  (471,'Power Split','http://bulbapedia.bulbagarden.net/wiki/Power_Split_(move)');
INSERT INTO PM_MOVE VALUES  (472,'Wonder Room','http://bulbapedia.bulbagarden.net/wiki/Wonder_Room_(move)');
INSERT INTO PM_MOVE VALUES  (473,'Psyshock','http://bulbapedia.bulbagarden.net/wiki/Psyshock_(move)');
INSERT INTO PM_MOVE VALUES  (474,'Venoshock','http://bulbapedia.bulbagarden.net/wiki/Venoshock_(move)');
INSERT INTO PM_MOVE VALUES  (475,'Autotomize','http://bulbapedia.bulbagarden.net/wiki/Autotomize_(move)');
INSERT INTO PM_MOVE VALUES  (476,'Rage Powder','http://bulbapedia.bulbagarden.net/wiki/Rage_Powder_(move)');
INSERT INTO PM_MOVE VALUES  (477,'Telekinesis','http://bulbapedia.bulbagarden.net/wiki/Telekinesis_(move)');
INSERT INTO PM_MOVE VALUES  (478,'Magic Room','http://bulbapedia.bulbagarden.net/wiki/Magic_Room_(move)');
INSERT INTO PM_MOVE VALUES  (479,'Smack Down','http://bulbapedia.bulbagarden.net/wiki/Smack_Down_(move)');
INSERT INTO PM_MOVE VALUES  (480,'Storm Throw','http://bulbapedia.bulbagarden.net/wiki/Storm_Throw_(move)');
INSERT INTO PM_MOVE VALUES  (481,'Flame Burst','http://bulbapedia.bulbagarden.net/wiki/Flame_Burst_(move)');
INSERT INTO PM_MOVE VALUES  (482,'Sludge Wave','http://bulbapedia.bulbagarden.net/wiki/Sludge_Wave_(move)');
INSERT INTO PM_MOVE VALUES  (483,'Quiver Dance','http://bulbapedia.bulbagarden.net/wiki/Quiver_Dance_(move)');
INSERT INTO PM_MOVE VALUES  (484,'Heavy Slam','http://bulbapedia.bulbagarden.net/wiki/Heavy_Slam_(move)');
INSERT INTO PM_MOVE VALUES  (485,'Synchronoise','http://bulbapedia.bulbagarden.net/wiki/Synchronoise_(move)');
INSERT INTO PM_MOVE VALUES  (486,'Electro Ball','http://bulbapedia.bulbagarden.net/wiki/Electro_Ball_(move)');
INSERT INTO PM_MOVE VALUES  (487,'Soak','http://bulbapedia.bulbagarden.net/wiki/Soak_(move)');
INSERT INTO PM_MOVE VALUES  (488,'Flame Charge','http://bulbapedia.bulbagarden.net/wiki/Flame_Charge_(move)');
INSERT INTO PM_MOVE VALUES  (489,'Coil','http://bulbapedia.bulbagarden.net/wiki/Coil_(move)');
INSERT INTO PM_MOVE VALUES  (490,'Low Sweep','http://bulbapedia.bulbagarden.net/wiki/Low_Sweep_(move)');
INSERT INTO PM_MOVE VALUES  (491,'Acid Spray','http://bulbapedia.bulbagarden.net/wiki/Acid_Spray_(move)');
INSERT INTO PM_MOVE VALUES  (492,'Foul Play','http://bulbapedia.bulbagarden.net/wiki/Foul_Play_(move)');
INSERT INTO PM_MOVE VALUES  (493,'Simple Beam','http://bulbapedia.bulbagarden.net/wiki/Simple_Beam_(move)');
INSERT INTO PM_MOVE VALUES  (494,'Entrainment','http://bulbapedia.bulbagarden.net/wiki/Entrainment_(move)');
INSERT INTO PM_MOVE VALUES  (495,'After You','http://bulbapedia.bulbagarden.net/wiki/After_You_(move)');
INSERT INTO PM_MOVE VALUES  (496,'Round','http://bulbapedia.bulbagarden.net/wiki/Round_(move)');
INSERT INTO PM_MOVE VALUES  (497,'Echoed Voice','http://bulbapedia.bulbagarden.net/wiki/Echoed_Voice_(move)');
INSERT INTO PM_MOVE VALUES  (498,'Chip Away','http://bulbapedia.bulbagarden.net/wiki/Chip_Away_(move)');
INSERT INTO PM_MOVE VALUES  (499,'Clear Smog','http://bulbapedia.bulbagarden.net/wiki/Clear_Smog_(move)');
INSERT INTO PM_MOVE VALUES  (500,'Stored Power','http://bulbapedia.bulbagarden.net/wiki/Stored_Power_(move)');
INSERT INTO PM_MOVE VALUES  (501,'Quick Guard','http://bulbapedia.bulbagarden.net/wiki/Quick_Guard_(move)');
INSERT INTO PM_MOVE VALUES  (502,'Ally Switch','http://bulbapedia.bulbagarden.net/wiki/Ally_Switch_(move)');
INSERT INTO PM_MOVE VALUES  (503,'Scald','http://bulbapedia.bulbagarden.net/wiki/Scald_(move)');
INSERT INTO PM_MOVE VALUES  (504,'Shell Smash','http://bulbapedia.bulbagarden.net/wiki/Shell_Smash_(move)');
INSERT INTO PM_MOVE VALUES  (505,'Heal Pulse','http://bulbapedia.bulbagarden.net/wiki/Heal_Pulse_(move)');
INSERT INTO PM_MOVE VALUES  (506,'Hex','http://bulbapedia.bulbagarden.net/wiki/Hex_(move)');
INSERT INTO PM_MOVE VALUES  (507,'Sky Drop','http://bulbapedia.bulbagarden.net/wiki/Sky_Drop_(move)');
INSERT INTO PM_MOVE VALUES  (508,'Shift Gear','http://bulbapedia.bulbagarden.net/wiki/Shift_Gear_(move)');
INSERT INTO PM_MOVE VALUES  (509,'Circle Throw','http://bulbapedia.bulbagarden.net/wiki/Circle_Throw_(move)');
INSERT INTO PM_MOVE VALUES  (510,'Incinerate','http://bulbapedia.bulbagarden.net/wiki/Incinerate_(move)');
INSERT INTO PM_MOVE VALUES  (511,'Quash','http://bulbapedia.bulbagarden.net/wiki/Quash_(move)');
INSERT INTO PM_MOVE VALUES  (512,'Acrobatics','http://bulbapedia.bulbagarden.net/wiki/Acrobatics_(move)');
INSERT INTO PM_MOVE VALUES  (513,'Reflect Type','http://bulbapedia.bulbagarden.net/wiki/Reflect_Type_(move)');
INSERT INTO PM_MOVE VALUES  (514,'Retaliate','http://bulbapedia.bulbagarden.net/wiki/Retaliate_(move)');
INSERT INTO PM_MOVE VALUES  (515,'Final Gambit','http://bulbapedia.bulbagarden.net/wiki/Final_Gambit_(move)');
INSERT INTO PM_MOVE VALUES  (516,'Bestow','http://bulbapedia.bulbagarden.net/wiki/Bestow_(move)');
INSERT INTO PM_MOVE VALUES  (517,'Inferno','http://bulbapedia.bulbagarden.net/wiki/Inferno_(move)');
INSERT INTO PM_MOVE VALUES  (518,'Water Pledge','http://bulbapedia.bulbagarden.net/wiki/Water_Pledge_(move)');
INSERT INTO PM_MOVE VALUES  (519,'Fire Pledge','http://bulbapedia.bulbagarden.net/wiki/Fire_Pledge_(move)');
INSERT INTO PM_MOVE VALUES  (520,'Grass Pledge','http://bulbapedia.bulbagarden.net/wiki/Grass_Pledge_(move)');
INSERT INTO PM_MOVE VALUES  (521,'Volt Switch','http://bulbapedia.bulbagarden.net/wiki/Volt_Switch_(move)');
INSERT INTO PM_MOVE VALUES  (522,'Struggle Bug','http://bulbapedia.bulbagarden.net/wiki/Struggle_Bug_(move)');
INSERT INTO PM_MOVE VALUES  (523,'Bulldoze','http://bulbapedia.bulbagarden.net/wiki/Bulldoze_(move)');
INSERT INTO PM_MOVE VALUES  (524,'Frost Breath','http://bulbapedia.bulbagarden.net/wiki/Frost_Breath_(move)');
INSERT INTO PM_MOVE VALUES  (525,'Dragon Tail','http://bulbapedia.bulbagarden.net/wiki/Dragon_Tail_(move)');
INSERT INTO PM_MOVE VALUES  (526,'Work Up','http://bulbapedia.bulbagarden.net/wiki/Work_Up_(move)');
INSERT INTO PM_MOVE VALUES  (527,'Electroweb','http://bulbapedia.bulbagarden.net/wiki/Electroweb_(move)');
INSERT INTO PM_MOVE VALUES  (528,'Wild Charge','http://bulbapedia.bulbagarden.net/wiki/Wild_Charge_(move)');
INSERT INTO PM_MOVE VALUES  (529,'Drill Run','http://bulbapedia.bulbagarden.net/wiki/Drill_Run_(move)');
INSERT INTO PM_MOVE VALUES  (530,'Dual Chop','http://bulbapedia.bulbagarden.net/wiki/Dual_Chop_(move)');
INSERT INTO PM_MOVE VALUES  (531,'Heart Stamp','http://bulbapedia.bulbagarden.net/wiki/Heart_Stamp_(move)');
INSERT INTO PM_MOVE VALUES  (532,'Horn Leech','http://bulbapedia.bulbagarden.net/wiki/Horn_Leech_(move)');
INSERT INTO PM_MOVE VALUES  (533,'Sacred Sword','http://bulbapedia.bulbagarden.net/wiki/Sacred_Sword_(move)');
INSERT INTO PM_MOVE VALUES  (534,'Razor Shell','http://bulbapedia.bulbagarden.net/wiki/Razor_Shell_(move)');
INSERT INTO PM_MOVE VALUES  (535,'Heat Crash','http://bulbapedia.bulbagarden.net/wiki/Heat_Crash_(move)');
INSERT INTO PM_MOVE VALUES  (536,'Leaf Tornado','http://bulbapedia.bulbagarden.net/wiki/Leaf_Tornado_(move)');
INSERT INTO PM_MOVE VALUES  (537,'Steamroller','http://bulbapedia.bulbagarden.net/wiki/Steamroller_(move)');
INSERT INTO PM_MOVE VALUES  (538,'Cotton Guard','http://bulbapedia.bulbagarden.net/wiki/Cotton_Guard_(move)');
INSERT INTO PM_MOVE VALUES  (539,'Night Daze','http://bulbapedia.bulbagarden.net/wiki/Night_Daze_(move)');
INSERT INTO PM_MOVE VALUES  (540,'Psystrike','http://bulbapedia.bulbagarden.net/wiki/Night_Daze_(move)');
INSERT INTO PM_MOVE VALUES  (541,'Tail Slap','http://bulbapedia.bulbagarden.net/wiki/Tail_Slap_(move)');
INSERT INTO PM_MOVE VALUES  (542,'Hurricane','http://bulbapedia.bulbagarden.net/wiki/Hurricane_(move)');
INSERT INTO PM_MOVE VALUES  (543,'Head Charge','http://bulbapedia.bulbagarden.net/wiki/Head_Charge_(move)');
INSERT INTO PM_MOVE VALUES  (544,'Gear Grind','http://bulbapedia.bulbagarden.net/wiki/Gear_Grind_(move)');
INSERT INTO PM_MOVE VALUES  (545,'Searing Shot','http://bulbapedia.bulbagarden.net/wiki/Searing_Shot_(move)');
INSERT INTO PM_MOVE VALUES  (546,'Techno Blast','http://bulbapedia.bulbagarden.net/wiki/Techno_Blast_(move)');
INSERT INTO PM_MOVE VALUES  (547,'Relic Song','http://bulbapedia.bulbagarden.net/wiki/Relic_Song_(move)');
INSERT INTO PM_MOVE VALUES  (548,'Secret Sword','http://bulbapedia.bulbagarden.net/wiki/Secret_Sword_(move)');
INSERT INTO PM_MOVE VALUES  (549,'Glaciate','http://bulbapedia.bulbagarden.net/wiki/Glaciate_(move)');
INSERT INTO PM_MOVE VALUES  (550,'Bolt Strike','http://bulbapedia.bulbagarden.net/wiki/Bolt_Strike_(move)');
INSERT INTO PM_MOVE VALUES  (551,'Blue Flare','http://bulbapedia.bulbagarden.net/wiki/Blue_Flare_(move)');
INSERT INTO PM_MOVE VALUES  (552,'Fiery Dance','http://bulbapedia.bulbagarden.net/wiki/Fiery_Dance_(move)');
INSERT INTO PM_MOVE VALUES  (553,'Freeze Shock','http://bulbapedia.bulbagarden.net/wiki/Freeze_Shock_(move)');
INSERT INTO PM_MOVE VALUES  (554,'Ice Burn','http://bulbapedia.bulbagarden.net/wiki/Ice_Burn_(move)');
INSERT INTO PM_MOVE VALUES  (555,'Snarl','http://bulbapedia.bulbagarden.net/wiki/Snarl_(move)');
INSERT INTO PM_MOVE VALUES  (556,'Icicle Crash','http://bulbapedia.bulbagarden.net/wiki/Icicle_Crash_(move)');
INSERT INTO PM_MOVE VALUES  (557,'V-create','http://bulbapedia.bulbagarden.net/wiki/V-create_(move)');
INSERT INTO PM_MOVE VALUES  (558,'Fusion Flare','http://bulbapedia.bulbagarden.net/wiki/Fusion_Flare_(move)');
INSERT INTO PM_MOVE VALUES  (559,'Fusion Bolt','http://bulbapedia.bulbagarden.net/wiki/Fusion_Bolt_(move)');